In [ ]:
### Homework 3 Numpy Arrays and Pandas

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into a numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [4]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


1. (2 pts) What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [15]:
#object , float, float and object
print(car.dtype)
print(mpg.dtype)
print(horsepower.dtype)
print(origin.dtype)

object
float64
float64
object


2. (1 pt) `numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [ ]:
#aliasing so we dont have to type nympy evrytime we call functions from the library

3. (2 pts) Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [19]:
#they all have 1 dimensions
print(car.ndim)
print(mpg.ndim)

1
1


4. (3 pts) What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help) (1 pt extra credit)

In [35]:
print("sum -", np.sum(horsepower))
print("min -", np.max(horsepower))
print("max -", np.min(horsepower))
print("median -", np.median(horsepower))
import statistics as st
print("mode -", st.mode(horsepower))

sum - 42033.0
min - 230.0
max - 0.0
median - 93.5
mode - 150.0


5. (2 pts) Select the last element in each subarray (do this with one operation.)

In [37]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])

In [47]:
a = np.array(select_more[:, 2])
a

array([3, 6, 9])

6. (2 pts) Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [58]:
np.lookfor('log')
a = np.array(np.log10(mpg))
a

Search results for 'log'
------------------------
numpy.log
    Natural logarithm, element-wise.
numpy.log2
    Base-2 logarithm of `x`.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, element-wise.
numpy.logspace
    Return numbers spaced evenly on a log scale.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.logical_or
    Compute the truth value of x1 OR x2 element-wise.
numpy.logical_and
    Compute the truth value of x1 AND x2 element-wise.
numpy.logical_not
    Compute the truth value of NOT x element-wise.
numpy.logical_xor
    Compute the truth value of x1 XOR x2, element-wise.
numpy.ma.log
    Natural logarithm, element-wise.
numpy.ma.log2
    Base-2 logarithm of `x`.
numpy.ma.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.rec

/var/folders/mg/lmrbfwqx6_zgt73dtvsgmyz00000gn/T/ipykernel_72230/3186263438.py:2: RuntimeWarning: divide by zero encountered in log10
  a = np.array(np.log10(mpg))


array([1.25527251, 1.17609126, 1.25527251, 1.20411998, 1.23044892,
       1.17609126, 1.14612804, 1.14612804, 1.14612804, 1.17609126,
             -inf,       -inf,       -inf,       -inf,       -inf,
       1.17609126, 1.14612804,       -inf, 1.17609126, 1.14612804,
       1.38021124, 1.34242268, 1.25527251, 1.32221929, 1.43136376,
       1.41497335, 1.39794001, 1.38021124, 1.39794001, 1.41497335,
       1.32221929, 1.        , 1.        , 1.04139269, 0.95424251,
       1.43136376, 1.44715803, 1.39794001, 1.39794001,       -inf,
       1.2787536 , 1.20411998, 1.23044892, 1.2787536 , 1.25527251,
       1.14612804, 1.14612804, 1.14612804, 1.14612804, 1.07918125,
       1.11394335, 1.11394335, 1.25527251, 1.34242268, 1.2787536 ,
       1.25527251, 1.36172784, 1.44715803, 1.47712125, 1.47712125,
       1.49136169, 1.54406804, 1.43136376, 1.41497335, 1.38021124,
       1.39794001, 1.36172784, 1.30103   , 1.32221929, 1.11394335,
       1.14612804, 1.17609126, 1.14612804, 1.23044892, 1.04139

7. (2 pts) Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [61]:
bool_arr = np.array(origin=='US')
print(bool_arr)

[ True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True False  True  True  True
 False False False False False False  True  True  True  True  True False
  True False  True False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True False False False
 False False False  True False  True False  True  True  True  True  True
  True  True  True  True  True  True False  True  True  True  True False
 False False False  True False False  True False  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True  True False  True False False  True
  True False  True  True False False False False  True False False  True
  True  True  True  True False  True False  True  True  True  True  True
  True  True  True  True False False False False False  True False False
 False False False  True  True  True  True  True  T

8. (2 pts) Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [70]:
print(car[bool_arr[:]])

['Chevrolet Chevelle Malibu' 'Buick Skylark 320' 'Plymouth Satellite'
 'AMC Rebel SST' 'Ford Torino' 'Ford Galaxie 500' 'Chevrolet Impala'
 'Plymouth Fury iii' 'Pontiac Catalina' 'AMC Ambassador DPL'
 'Chevrolet Chevelle Concours (sw)' 'Ford Torino (sw)'
 'Plymouth Satellite (sw)' 'AMC Rebel SST (sw)' 'Dodge Challenger SE'
 "Plymouth 'Cuda 340" 'Ford Mustang Boss 302' 'Chevrolet Monte Carlo'
 'Buick Estate Wagon (sw)' 'Plymouth Duster' 'AMC Hornet' 'Ford Maverick'
 'AMC Gremlin' 'Ford F250' 'Chevy C20' 'Dodge D200' 'Hi 1200D'
 'Chevrolet Vega 2300' 'Ford Pinto' 'AMC Gremlin'
 'Plymouth Satellite Custom' 'Chevrolet Chevelle Malibu' 'Ford Torino 500'
 'AMC Matador' 'Chevrolet Impala' 'Pontiac Catalina Brougham'
 'Ford Galaxie 500' 'Plymouth Fury iii' 'Dodge Monaco (sw)'
 'Ford Country Squire (sw)' 'Pontiac Safari (sw)'
 'AMC Hornet Sportabout (sw)' 'Chevrolet Vega (sw)' 'Pontiac Firebird'
 'Ford Mustang' 'Mercury Capri 2000' 'Plymouth Cricket'
 'Dodge Colt Hardtop' 'Chevrolet Vega' 'Ford

### Use numpy or pandas to answer the following questions.

9. (3 pts) What is the average horsepower for `Europe` cars? (Hint: create a boolean index of 'US' apply it to horsepower and perform the calculation.)

In [72]:
bool= np.array(origin=='Europe')
Average = np.mean(horsepower[bool[:]])
print(Average)

78.78082191780823


10. (3 pts) On average are Japanese cars more fuel-efficient than US cars? Show the code that you used to determine this.  

In [80]:
Japanese= np.array(origin=='Japan')
J_eff = np.mean(mpg[Japanese[:]])
US_cars = np.array(origin=='US')
US_eff = np.mean(mpg[US_cars[:]])
if J_eff> US_eff:
    print('Japanese cars are more fuel-efficent')
else:
    print('US cars are more fuel-efficient')

Japanese cars are more fuel-efficent


11. (3 pts) What is the correlation coefficient of `mpg` and `weight`? What is a correlation coefficient?

In [82]:
#coefficient variable is how much changes in two variable affect eachother
df = pd.read_csv('cars.csv',delimiter=';')
np.corrcoef(df['MPG'], df['Weight'])

array([[ 1.        , -0.78750994],
       [-0.78750994,  1.        ]])

Extra credit: (3 pts) Create a new pandas dataframe that has the average mpg, weight, and horsepower per country of origin

In [97]:
Per_country_df = df.groupby("Origin")
df1 = Per_country_df[['MPG']].mean()
df2 = Per_country_df[['Weight']].mean()
df3 = Per_country_df[['Horsepower']].mean()

In [107]:
df4=df1.merge(df2, how='inner', on='Origin')
new_df=df4.merge(df3, how='inner', on='Origin')
new_df

MPG       Weight  Horsepower
Origin                                    
Europe  26.745205  2431.493151   78.780822
Japan   30.450633  2221.227848   79.835443
US      19.688189  3372.700787  118.011811